#!/bin/bash

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
	echo "No commits to push!"
	exit 0
fi

read -p "You're about to push, are you sure you won't break the build? " -n 1 -r < /dev/tty
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	CMD="npm run build:release" # Command that runs your tests
	protected_master='master'
	protected_development='development'

	current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

	# if [ $current_branch = $protected_master ] || [ $current_branch = $protected_development ] ; then
		echo "Then you woudn't mind if I test..."
		$CMD
		RESULT=$?
		if [ $RESULT -ne 0 ]; then 
			echo "failed $CMD"
			exit 1
		fi
	# fi
	exit 0
fi
exit 1
